version: '2.375.3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net: 
